### ISSUE TITLE
Error on index.js:14:34

### ISSUE THREAD

**Issue by vteran93** [trek10inc/serverless-cloudformation-parameters#5]
Hi, I am getting the described below error and I am not sure why.

Someone could give me a hand. 

This is my serverless.yml file 
```yml

service: someservice

provider:
  name: aws
  runtime: python3.8
  region: us-east-2

plugins:
  - serverless-wsgi
  - serverless-python-requirements
  - serverless-cloudformation-parameter-setter

  cf-parameters:
    MasterUsernameParameter: postgres
    MasterUserPasswordParameter: something

functions:
  graphql:
    handler: wsgi_handler.handler
    events:
      - http: ANY /
      - http: ANY /{proxy+}

  #other_task:
    #handler: some_script.handler

custom:
  wsgi:
    app: python_project.wsgi.app

  pythonRequirements:
    dockerizePip: non-linux
    slim: true

  cf-parameters:
    MasterUsernameParameter: postgres
    MasterUserPasswordParameter: something

package:
  patterns:
    - '!node_modules/**'
    - '!docker-compose.yml'
    - '!**/__pycache__'
    - '!**/test/**'

resources:
  Parameters:
    environmentParameter:
      Description: An environment variable
      Type: String
      Default: dev
...

```

```js
| found 0 vulnerabilities
| Error initializing serverless-cloudformation-parameters SyntaxError: Unexpected token '{'
|     at Function (<anonymous>)
|     at new ServerlessCloudFormationParameterSetter (/home/victor_teran/repositories/some/node_modules/serverless-cloudformation-parameter-setter/index.js:14:34)
|     at PluginManager.addPlugin (/home/victor_teran/repositories/some/node_modules/serverless/lib/classes/plugin-manager.js:91:28)
|     at /home/victor_teran/repositories/some/node_modules/serverless/lib/classes/plugin-manager.js:137:69
|     at Array.forEach (<anonymous>)
|     at PluginManager.loadAllPlugins (/home/victor_teran/repositories/some/node_modules/serverless/lib/classes/plugin-manager.js:137:44)
|     at async Serverless.init (/home/victor_teran/repositories/some/node_modules/serverless/lib/serverless.js:141:5)
|     at async /home/victor_teran/repositories/some/node_modules/serverless/scripts/serverless.js:591:7
| Environment: linux, node 16.15.1, framework 3.18.2 (local), plugin 6.2.2, SDK 4.3.2
| Docs:        docs.serverless.com
| Support:     forum.serverless.com
| Bugs:        github.com/serverless/serverless/issues
|
| Error:
| SyntaxError: Unexpected token '{'
|     at Function (<anonymous>)
|     at new ServerlessCloudFormationParameterSetter (/home/victor_teran/repositories/some/node_modules/serverless-cloudformation-parameter-setter/index.js:14:34)
|     at PluginManager.addPlugin (/home/victor_teran/repositories/some/node_modules/serverless/lib/classes/plugin-manager.js:91:28)
|     at /home/victor_teran/repositories/some/node_modules/serverless/lib/classes/plugin-manager.js:137:69
|     at Array.forEach (<anonymous>)
|     at PluginManager.loadAllPlugins (/home/victor_teran/repositories/some/node_modules/serverless/lib/classes/plugin-manager.js:137:44)
|     at async Serverless.init (/home/victor_teran/repositories/some/node_modules/serverless/lib/serverless.js:141:5)
|     at async /home/victor_teran/repositories/some/node_modules/serverless/scripts/serverless.js:591:7
[Deploy main branch/deploy]   ❌  Failure - Install npm dependencies and deploy
```
